version: '3.7'

services:

    application:
        container_name: application
        tty: true
        build:
          context: ./node
          dockerfile: Dockerfile
        entrypoint: dockerize -wait tcp://dbt:3306 -timeout 20s sh -c "npm run dev"
        volumes:
          - ./:/usr/src/app
        networks:
            - node-network
        depends_on: 
            - dbt 

    nginx:
        build:
           context: ./nginx
           dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - application
        networks:
            - node-network


    dbt:
        image: mysql:5.7
        container_name: dbt
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
            - ./node/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=nodetest
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network



volumes:
  dbt:
    driver: "local"


networks:
  node-network:
    driver: bridge
